server:
  port: 8084

spring:
  application:
    name: MarketGateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: item
          uri: lb://ITEM
          predicates:
            - Path=/item/**
        - id: auction
          uri: lb://AUCTION
          predicates:
            - Path=/auction/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true